{% set name = "sphinx-llms-txt" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sphinx_llms_txt-{{ version }}.tar.gz
  sha256: e632108dd4444600df8018262b3c9cbd3d4c470db7c6f28912baacd99ada1b4e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - sphinx_llms_txt
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
    - sphinx

about:
  home: https://github.com/jdillard/sphinx-llms-txt
  summary: llms-full.txt generator for Sphinx
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/jdillard/sphinx-llms-txt
  doc_url: https://sphinx-llms-txt.readthedocs.io

extra:
  recipe-maintainers:
    - jdillard
